name: Update Movie Cover Image URL

on:
  push:
    branches:
      - main

jobs:
  update-movie-cover-image-url:
    name: Change NeoDB-Movie Domain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 检查是否安装了 JQ
      - name: Check JQ
        run: |
          if ! command -v jq &> /dev/null; then
            echo "jq is not installed. Installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          else
            echo "jq is already installed."
          fi
          # 把当前目录保存到环境变量中
          echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

      #更新
      - name: Update cover_image_url in movies.json
        run: |
          # 读取本地的 movies.json 文件内容
          movies=$(jq -c '.data' data/neodb/movies.json)
          for movie in $movies; do
          old_url=$(echo $movie | jq -r '.item.cover_image_url')
          new_url="${old_url//https:\/\/neodb.social/https:\/\/neodb.prvcy.page}" # 示例：替换 https://neodb.social 为 https://neodb.prvcy.page
          echo "Old cover_image_url: $old_url"
          echo "New cover_image_url: $new_url"
          jq --arg new_url "$new_url" '.item.cover_image_url = $new_url' <<< "$movie" > /tmp/temp_movie.json && mv /tmp/temp_movie.json <<< "$movie"
          done
          cp data/neodb/movies.json data/neodb/movies_updated.json
          jq -c '.data[]' <(printf '%s\n' "$movies") > data/neodb/movies_updated.json

      # 把修改后的数据提交到 GitHub 仓库
      - name: Git Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update cover image URL in movies_updated.json'
          add: './data/neodb'
